version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-deps:
        patterns: ['*']
  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
    groups:
      client-deps:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: monthly
